services:
  jupyter:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jarvis-jupyter
    ports:
      - "8888:8888"
    volumes:
      - .:/workspace
    command: jupyter lab --ip=0.0.0.0 --no-browser --allow-root
    environment:
      - JUPYTER_ENABLE_LAB=yes