version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis_audio
    ports:
      - "6379:6379"
    command: >
      redis-server 
      --appendonly yes 
      --save 60 1 
      --save 300 100 
      --save 900 1000
      --maxmemory 1000mb
    volumes:
      - ./redis_data:/data
  tts:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "5000:5000"
    environment:
      - REDIS_URL=redis://redis:6379
      - NARKEE_API_KEY=${NARKEE_API_KEY}
    depends_on:
      - redis 
