version: '2.1'

services:
  chroma:
    image: chromadb/chroma
    container_name: chromadb
    restart: always
    networks:
      - backend
    expose:     # Only available inside Docker
      - "8000"  # Ensure correct binding
    volumes:
      - chroma_data:/chroma

  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    networks:
      - backend
    expose:
      - "27017"
    volumes:
      - mongo_data:/data/db
    command: ["mongod", "--quiet", "--bind_ip", "0.0.0.0", "--logpath", "/dev/null"] # Mutes mongodb logs except errors using --logpath /dev/null
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  llm-service:
    depends_on:
      - chroma
      - mongodb
    build: ./core
    restart: unless-stopped
    environment:
      FLASK_ENV: ${FLASK_ENV}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      LANGSMITH_API_KEY: ${LANGSMITH_API_KEY}
      LANGCHAIN_TRACING_V2: ${LANGCHAIN_TRACING_V2}
      LANGCHAIN_ENDPOINT: "https://api.smith.langchain.com"
      LANGCHAIN_PROJECT: ${LANGCHAIN_PROJECT}
      PERPLEXITY_API_KEY: ${PERPLEXITY_API_KEY}
      GOOGLE_AUTH_KEY: ${GOOGLE_AUTH_KEY}
      GOOGLE_CALENDAR_ID: ${GOOGLE_CALENDAR_ID}
      PORT: ${PORT}
      TAVILY_API_KEY: ${TAVILY_API_KEY}
      Port_STT: ${PORT_STT}
    volumes:
      - ./core:/app  # Mount application for live changes
    networks:
      - backend
    ports:
      - "3000:3000"
      - "11434:11434"
    deploy:
      resources:
        limits:
          cpus: '1' # CPU limit
          memory: 2gb  # Memory limit

  speech-to-text:
    build: ./speechToText
    restart: unless-stopped
    environment:
      FLASK_ENV: ${FLASK_ENV}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      PORT_STT: ${PORT_STT}
    volumes:
      - ./speechToText:/app
    networks:
      - backend
    ports:
      - "3001:3001"

  redis:
    image: redis:latest
    container_name: redis_audio
    restart: always
    expose:
      - "6379"
    networks:
      - backend
    command: >
      redis-server 
      --appendonly yes 
      --save 60 1 
      --save 300 100 
      --save 900 1000
      --maxmemory 1gb
    volumes:
      - redis_data:/data

  tts:
    build:
      context: ./textToSpeech
      dockerfile: Dockerfile
    networks:
      - backend
    env_file:
      - .env
    ports:
      - "5001:5001"
    environment:
      - REDIS_URL=redis://redis:6379
      - NARKEE_API_KEY=${NARKEE_API_KEY}
    depends_on:
      - redis

volumes:
  chroma_data:  # Persistent storage for ChromaDB
  mongo_data:   # Persistent storage for MongoDB
  redis_data:   # Persistent storage for Redis

networks:
  backend:
    driver: bridge
