services:
  llm-service:
    build: ./core
    restart: unless-stopped
    environment:
      FLASK_ENV: ${FLASK_ENV} # Autorestarts flask when code changes are detected
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      LANGSMITH_API_KEY: ${LANGSMITH_API_KEY}
      PORT: ${PORT}
    volumes:
      - ./core:/app  # Mount the application code to detect live changes
    networks:
      - backend
    stop_signal: SIGINT
    ports:
      - "3000:3000"

  speech-to-text:
    build: ./speechToText
    restart: unless-stopped
    environment:
      FLASK_ENV: ${FLASK_ENV} # Autorestarts flask when code changes are detected
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      PORT_STT: ${PORT_STT}
    volumes:
      - ./speechToText:/app  # Mount the application code to detect live changes
    networks:
      - backend
    stop_signal: SIGINT
    ports:
      - "3001:3001"

networks:
  backend:
    driver: bridge