version: '3.8'

services:
  ui-service:
    build: ./ui
    env_file: .env
    restart: unless-stopped
    volumes:
      - ./ui:/app  # Mount the application code
      - /app/node_modules
    networks:
      - backend
    stop_signal: SIGINT
    ports:
      - "3000:3000"

#  llm-service:
#    build: ./core
#    env_file: .env
#    restart: unless-stopped
#    environment:
#      - FLASK_ENV=development # Autorestarts flask when code changes are detected
#    volumes:
#      - ./core:/app  # Mount the application code to detect live changes
#    networks:
#      - backend
#    stop_signal: SIGINT
#    ports:
#      - "3001:3001"

#  speech-service:
#    build: ./speech
#    env_file: .env
#    restart: unless-stopped
#    environment:
#    volumes:
#      - ./speech:/app
#    networks:
#      - backend
#    stop_signal: SIGINT
 #   ports:
 #     - "3069:3069" #nice

networks:
  backend:
    driver: bridge