services:

  llm-service:
    build: ./core
    env_file: .env
    restart: unless-stopped
    environment:
      - FLASK_ENV=development # Autorestarts flask when code changes are detected
    volumes:
      - ./core:/app  # Mount the application code to detect live changes
    networks:
      - backend
    stop_signal: SIGINT
    ports:
      - "3000:3000"


networks:
  backend:
    driver: bridge