services:
  llm-service:
    build: ./core
    restart: unless-stopped
    environment:
      FLASK_ENV: ${FLASK_ENV} # Autorestarts flask when code changes are detected
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      LANGSMITH_API_KEY: ${LANGSMITH_API_KEY}
      LANGCHAIN_TRACING_V2: true
      LANGCHAIN_ENDPOINT: "https://api.smith.langchain.com"
      LANGCHAIN_PROJECT: ${LANGCHAIN_PROJECT}
      PERPLEXITY_API_KEY: ${PERPLEXITY_API_KEY}
      GOOGLE_AUTH_KEY: ${GOOGLE_AUTH_KEY}
      GOOGLE_CALENDAR_ID: ${GOOGLE_CALENDAR_ID}
      PORT: ${PORT}
    volumes:
      - ./core:/app  # Mount the application code to detect live changes
    networks:
      - backend
    stop_signal: SIGINT
    ports:
      - "3000:3000"


networks:
  backend:
    driver: bridge